# use Docker-based container (instead of OpenVZ)
sudo: false

branches:
  only:
    - master
    - dev

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.12.8
  - 2.11.12

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - git config user.email wtgeeker@163.com
  - git config user.name wtog
  - current=`git log | head -n 1 | awk '{print $2}'`
  - if [ "$TRAVIS_BRANCH" = 'dev' ]; then \
      git pull origin master:master \
      git checkout master \
      git merge $current \
      git push \
    else
      sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("NEXUS_USER"), System.getenv("NEXUS_PASS"))' \
      'set pgpPassphrase := Some("PGP_PASSPHRASE".toArray[Char])' \
      ++$TRAVIS_SCALA_VERSION clean publish \
    fi
