# use Docker-based container (instead of OpenVZ)
sudo: false

branches:
  only:
    - dev

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script:
  - wget -q https://npm.taobao.org/mirrors/chromedriver/70.0.3538.16/chromedriver_linux64.zip
  - unzip -x chromedriver_linux64.zip -d /opt
  - sbt -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=System.getenv("SONAR_TOKEN") ';clean ;coverage ;test ;coverageReport'

jdk:
  - openjdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sbt ';set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("NEXUS_USER"), System.getenv("NEXUS_PASS")); set pgpPassphrase := Some("PGP_PASSPHRASE".toArray[Char]); +clean; +publish';
  - git config --global user.email wtgeeker@163.com
  - git config --global user.name wtog
  - current=`git log | head -n 1 | awk '{print $2}'`
  - git fetch origin master:master; git checkout master; git merge $current -s recursive -X theirs --no-commit;
  - git commit -m `git log $current --oneline | head -n 1 | awk '{print $2}'`
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/wtog/web-crawler.git" master:master
