# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile publish

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.12.8
  - 2.11.12

jdk:
  - oraclejdk8
  - openjdk8
