# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script:
  - sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("NEXUS_USER"), System.getenv("NEXUS_PASS"))'
    'usePgpKeyHex("PGP_KEY")'
    'set pgpPassphrase := Some("PGP_PASSPHRASE".toArray[Char])'
    ++$TRAVIS_SCALA_VERSION compile publishSigned

  - find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.12.8
  - 2.11.12

jdk:
  - oraclejdk8
  - openjdk8
