# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script:
  - sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("NEXUS_USER"), System.getenv("NEXUS_PASS"))'
    'set pgpPassphrase := Some("PGP_PASSPHRASE".toArray[Char])'
    ++$TRAVIS_SCALA_VERSION clean compile coverage test coverageReport publish

  - find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.12.8
  - 2.11.12

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash) -t System.getenv("CODECOV_TOKEN")